### ISSUE TITLE
error

### ISSUE THREAD

**Issue by geometry88** [solero/wand#2]
ERROR: for 523a25a1f29c_wand_web_1  Cannot start service web: driver failed programming external connectivity on endpoint 523a25a1f29c_wand_web_1 (5df62252b95e007eae2db3900fdba1735cb1310b846cf4ef75d46c614787aeef): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint 523a25a1f29c_wand_web_1 (5df62252b95e007eae2db3900fdba1735cb1310b846cf4ef75d46c614787aeef): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by ketnipz** [comment]
This means that you have a web server already running elsewhere on the system.

If you have Apache or nginx installed already you need to stop them and/or remove them.

Alternatively. you can run them alongside wand by changing `WEB_PORT` in `.env` and proxying it with the web-server you have installed already.
