### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by arnon001** [solero/wand#22]
Hey there!,
I'm having problems with hosting wand with AARCH64 Machine,
There is anything I can do in order to fix it?.

**Comment by AllinolCP** [comment]
We do not currently support ARM. You'd have to swap every docker image for it, with that said Good Luck!

**Comment by thePublicer** [comment]
I Did some modifications to make this run on arm

**Comment by thePublicer** [comment]
[arm64.patch](https://github.com/solero/wand/files/12447223/arm64.patch)

**Comment by thePublicer** [comment]
[arm64.patch](https://github.com/solero/wand/files/12447260/arm64.patch)

**Comment by thePublicer** [comment]
here's the patch

**Comment by arnon001** [comment]
Can you send me a message in discord and you'll help me with it please?
arnon001

**Comment by AllinolCP** [comment]
> here's the patch

Great! You should make a Pull Request to add ARM support

**Comment by arnon001** [comment]
> > here's the patch
> 
> Great! You should make a Pull Request to add ARM support

can you help me with the where to put it or how to use it?

**Comment by thePublicer** [comment]
> > here's the patch
> 
> Great! You should make a Pull Request to add ARM support

Okay

**Comment by thePublicer** [comment]
check the commit
