### ISSUE TITLE
SendGrid 500 - internal server error

### ISSUE THREAD

**Issue by idrkwhattoput** [solero/wand#23]
When i put my sengrid api key it gives an error saying that http://play.localhost/create/vanilla/en (is not available 403 request) if i try to create a penguin it gives the 500 - internal server error message, im pretty sure this is not related to website and dns things because i saw people testing the email api in the setup guide with a localhosted website, here is the logs: 

also i don't have a sender verified, don't know if its needed

> web_1                | 172.18.0.1 - - [06/Oct/2023:00:25:07 +0000] "POST /en/penguin/create HTTP/1.1" 200 227 "http://play.localhost/penguin/create" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) FlashBrowser/0.0.1 Chrome/87.0.4280.141 Electron/11.5.0 Safari/537.36" "-"
> dash_1               | [2023-10-06 00:25:12 +0000] [11] [ERROR] Exception occurred while handling uri: 'http://play.localhost/create/vanilla/en'
> dash_1               | Traceback (most recent call last):
> dash_1               |   File "handle_request", line 83, in handle_request
> dash_1               |     )
> dash_1               |       
> dash_1               |   File "/usr/src/dash/dash/routes/create/vanilla.py", line 109, in register
> dash_1               |     return await _validate_registration(request, lang)
> dash_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> dash_1               |   File "/usr/src/dash/dash/routes/create/vanilla.py", line 192, in _validate_registration
> dash_1               |     sg.send(message)
> dash_1               |   File "/usr/local/lib/python3.11/site-packages/sendgrid/base_interface.py", line 62, in send
> dash_1               |     return self.client.mail.send.post(request_body=message)
> dash_1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> dash_1               |   File "/usr/local/lib/python3.11/site-packages/python_http_client/client.py", line 277, in http_request
> dash_1               |     self._make_request(opener, request, timeout=timeout)
> dash_1               |   File "/usr/local/lib/python3.11/site-packages/python_http_client/client.py", line 184, in _make_request
> dash_1               |     raise exc
> dash_1               | python_http_client.exceptions.ForbiddenError: HTTP Error 403: Forbidden
> web_1                | 172.18.0.1 - - [06/Oct/2023:00:25:12 +0000] "POST /en/penguin/create/ HTTP/1.1" 500 799 "http://play.localhost/penguin/create" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) FlashBrowser/0.0.1 Chrome/87.0.4280.141 Electron/11.5.0 Safari/537.36" "-"
> dash_1               | [2023-10-06 00:25:12 +0000] - (sanic.access)[INFO][172.18.0.10:47858]: POST http://play.localhost/create/vanilla/en  500 799
>

**Comment by AllinolCP** [comment]
It does need the sender verified

**Comment by idrkwhattoput** [comment]
> It does need the sender verified

hello, i got the error being fixed by editing the "FROM_EMAIL =" to FROM_EMAIL = 'noreply@xxx.xxx' but for some reason it didn't send me the email i tried putting my email in the "Resend actvation email" screen but it just give a weird #2032 error...

![Captura de tela de 2023-10-06 19-43-03](https://github.com/solero/wand/assets/146492894/59d465a0-d654-471d-b55c-89261c60500c)
![Captura de tela de 2023-10-06 19-46-18](https://github.com/solero/wand/assets/146492894/7cf2d611-5c81-44ef-9330-1f4d5372166f)

**Comment by AllinolCP** [comment]
> >  weird #2032 error...
It does not have this implemented, so this isn't a wand issue

**Comment by ikwhattoput** [comment]
> > weird #2032 error...
> 
> It does not have this implemented, so this isn't a wand issue

hello i fixed the email sending by just simply restarting the server, im not in my op account rn so you can mark this as solved

![Captura de tela de 2023-10-07 11-16-45](https://github.com/solero/wand/assets/120697787/9594378a-958e-4aa5-bc2b-1ac6e1cc8a09)
