### ISSUE TITLE
Python 3.12 Issue - Found Fix

### ISSUE THREAD

**Issue by EAZYBLACK** [solero/wand#24]
Ok so python building depencies fails
cuz of python 3.12 being the default
as the dockerfile is set to download latest
so in houdini/Dockerfile and dash/Dockerfile
i changed the first line from this FROM python:3-alpine
to this 
FROM python:3.9-alpine
and that fixed the issue, i used python 3.9 as it should work!

**Comment by sudocbreaux** [comment]
oh my god dude thank you. its 7am right now ive been trying to figure this out all night

**Comment by AllinolCP** [comment]
Hi there, could any of you post the error so I can officially update houdini/dash to python 3.12.

**Comment by EAZYBLACK** [comment]
> Hi there, could any of you post the error so I can officially update houdini/dash to python 3.12.

uvloop fails and aiohttp may fail too
